--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/shreyop200/AuthUI
build-by-default: true
branches:
- main
projects: 
  AuthUI:
    path: ""
    icon: "resources/authentication.png"
...

