name: AuthUI
main: shreyop200\AuthUI\Auth
src-namespace-prefix: shreyop200\AuthUI
api:
- 4.0.0
- 5.0.0
version: 0.1.0
load: POSTWORLD
website: https://wenpixel.games
description: A Plugin To Manage your Security With AuthUI
author: shreyop200, Dimey

permissions:
 authui.use:
  default: true
  description: "Allows the player to use authui"

 authui.command.reload:
  default: op
  description: "Allows the player to use reload command"
