name: AuthUI
main: shreyop200\AuthUI\Main

api: [4.20.0, 5.0.0]
version: 2.0
website: https://wenpixel.games
description: A Plugin To Manage your Security With AuthUI
author: shreyop200

commands: 
  loginreload: 
    description: Reload player data
    permission: authui.command.reload
    
  unregister:
    description: Unregister a player
    permission: authui.command.unregister

permissions:
  authui.use:
    default: true
    description: "Allows the player to use authui"
 
  authui.command.reload:
    default: op
    description: "Allows the player to use reload command"
    
  authui.command.unregister:
    default: op
    description: "Allows the player to use unregister command"
