name: AuthUI
main: shreyop200\AuthUI\Main

api: 4.20
version: 0.1.0
website: https://wenpixel.games
description: A Plugin To Manage your Security With AuthUI
author: shreyop200

commands: 
  loginreload: 
    description: Reload player data 
    usage: /loginreload
    permission: authui.command.reload

permissions:
  authui.use:
    default: true
    description: "Allows the player to use authui"
 
  authui.command.reload:
    default: op
    description: "Allows the player to use reload command"
